"""empty message

Revision ID: af41a21ca961
Revises: e2fe94a19ca4
Create Date: 2020-09-06 00:20:59.432646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af41a21ca961'
down_revision = 'e2fe94a19ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('list_books_book_id_key', 'list_books', type_='unique')
    op.execute('ALTER TABLE list_books DROP CONSTRAINT list_books_pkey')
    op.execute('ALTER TABLE list_books ADD PRIMARY KEY (list_id, book_id)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('list_books_book_id_key', 'list_books', ['book_id'])
    # ### end Alembic commands ###
