"""empty message

Revision ID: e189cae5c2ec
Revises: 
Create Date: 2020-08-26 15:14:34.687331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e189cae5c2ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('authors', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('goodreads_average_rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('average_rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('isbn', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('isbn13', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('language_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('num_pages', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ratings_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goodreads_ratings_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goodreads_text_reviews_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='book_pkey'),
    sa.UniqueConstraint('isbn', name='book_isbn_key'),
    sa.UniqueConstraint('isbn13', name='book_isbn13_key')
    )
    # ### end Alembic commands ###
