"""empty message

Revision ID: e2fe94a19ca4
Revises: a209300d4b3c
Create Date: 2020-09-05 14:35:50.039271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2fe94a19ca4'
down_revision = 'a209300d4b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'list_books', 'list', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'list_books', type_='foreignkey')
    # ### end Alembic commands ###
